DROP SCHEMA PUBLIC CASCADE;
-- https://stackoverflow.com/questions/12918407/hsqldb-object-name-already-exists
DROP TABLE IF EXISTS menu_item;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS vote_log;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS dish;
DROP TABLE IF EXISTS restaurant;

DROP
SEQUENCE IF EXISTS global_seq;

CREATE
SEQUENCE global_seq START
WITH 100000;

CREATE TABLE dish
(
    id   INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT dish_unique_name_idx UNIQUE (name)
);

CREATE TABLE restaurant
(
    id         INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    name       VARCHAR(255)         NOT NULL,
    CONSTRAINT restaurant_unique_name_idx UNIQUE (name)
);

CREATE TABLE menu_item
(
    id            INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    date          DATE              NOT NULL,
    restaurant_id INTEGER           NOT NULL,
    dish_id       INTEGER           NOT NULL,
    price         DECIMAL DEFAULT 0 NOT NULL,
    CONSTRAINT menu_item_unique_date_restaurant_dish_idx UNIQUE (date, restaurant_id, dish_id),
    FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) ON DELETE CASCADE
);

CREATE TABLE users
(
    id         INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    name       VARCHAR(255)            NOT NULL,
    email      VARCHAR(255)            NOT NULL,
    password   VARCHAR(255)            NOT NULL,
    registered TIMESTAMP DEFAULT now() NOT NULL,
    enabled    BOOLEAN   DEFAULT TRUE  NOT NULL
);
CREATE UNIQUE INDEX users_unique_email_idx ON users (email);

CREATE TABLE user_roles
(
    user_id INTEGER NOT NULL,
    role    VARCHAR(255),
    CONSTRAINT user_roles_idx UNIQUE (user_id, role),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE vote_log
(
    id            INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    user_id       INTEGER NOT NULL,
    restaurant_id INTEGER NOT NULL,
    date          DATE    NOT NULL,
    CONSTRAINT user_date_idx UNIQUE (user_id, date),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) ON DELETE CASCADE
);